# Site settings
name: Danya Kim
title: Blog
email: itsdanya@gmail.com
description: "Code. Startups. Ideas."
baseurl: ""
url: "http://danyakim.com"

# Build settings
markdown: kramdown
permalinks: pretty

# Pagination
paginate: 10

# Details for the RSS feed generator
author: Danya Kim

# Style
logo: false