# Site settings
title: Danya Kim
email:
description: "Code, startups, ideas."
baseurl: ""
url: "http://danya.im"
twitter_username: idanyakim
github_username:  danyakim

# Build settings
markdown: kramdown
permalink: /:year/:title

gems:
  - jekyll-sitemap