# Site settings
title: Danya Kim
email: itsdanya@gmail.com
description: "Code, startups, ideas."
baseurl: ""
url: "http://danyakim.com"
twitter_username: idanyakim
github_username:  danyakim

# Build settings
markdown: kramdown
permalink: /:year/:title

gems:
  - jekyll-sitemap